<?php

/* custom routes generated by CRUD */


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('categories', ['as'=> 'categories.index', 'uses' => 'CategoryController@index']);
Route::post('categories', ['as'=> 'categories.store', 'uses' => 'CategoryController@store']);
Route::get('categories/create', ['as'=> 'categories.create', 'uses' => 'CategoryController@create']);
Route::put('categories/{categories}', ['as'=> 'categories.update', 'uses' => 'CategoryController@update']);
Route::patch('categories/{categories}', ['as'=> 'categories.update', 'uses' => 'CategoryController@update']);
Route::get('categories/{id}/delete', array('as' => 'categories.delete', 'uses' => 'CategoryController@getDelete'));
Route::get('categories/{id}/confirm-delete', array('as' => 'categories.confirm-delete', 'uses' => 'CategoryController@getModalDelete'));
Route::get('categories/{categories}', ['as'=> 'categories.show', 'uses' => 'CategoryController@show']);
Route::get('categories/{categories}/edit', ['as'=> 'categories.edit', 'uses' => 'CategoryController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('categories', ['as'=> 'categories.index', 'uses' => 'CategoryController@index']);
Route::post('categories', ['as'=> 'categories.store', 'uses' => 'CategoryController@store']);
Route::get('categories/create', ['as'=> 'categories.create', 'uses' => 'CategoryController@create']);
Route::put('categories/{categories}', ['as'=> 'categories.update', 'uses' => 'CategoryController@update']);
Route::patch('categories/{categories}', ['as'=> 'categories.update', 'uses' => 'CategoryController@update']);
Route::get('categories/{id}/delete', array('as' => 'categories.delete', 'uses' => 'CategoryController@getDelete'));
Route::get('categories/{id}/confirm-delete', array('as' => 'categories.confirm-delete', 'uses' => 'CategoryController@getModalDelete'));
Route::get('categories/{categories}', ['as'=> 'categories.show', 'uses' => 'CategoryController@show']);
Route::get('categories/{categories}/edit', ['as'=> 'categories.edit', 'uses' => 'CategoryController@edit']);

});
